### ISSUE TITLE
ephys: too large to download

### ISSUE THREAD

**Issue by tmorshed** [AllenInstitute/deepinterpolation_paper#1]
#### Issue description
The ephys file is too large for free-tier Dropbox users to download.

#### Steps to reproduce the issue

1. Sign out of any licensed Dropbox account
2. Open the link for the ophys dataset (which was provided at `../deepinterpolation_paper/data/local_large_data/`). The link is https://www.dropbox.com/sh/uls0ts6bbi5l7gl/AAAyubqXjkazrg7rxXbbKTBYa.
3. Click "Download" from the top bar.

#### What's the expected result?

- File starts downloading

#### What's the actual result?

- Resulting error message: _"The zip file is too large"_

#### Screenshot

![image](https://user-images.githubusercontent.com/14872591/111071079-e8cd2f80-84aa-11eb-919f-afe02d4007c7.png)

#### Possible reason(s):

- Per [this discussion](https://www.dropboxforum.com/t5/Dropbox-files-folders/How-to-download-large-files-and-folders-from-Dropbox/td-p/220123) on the Dropbox help forum, the download limit for free-tier users is 1GB or 10,000 files per day.

#### Possible solution(s):

Either of:
- Zip the whole folder before uploading to Dropbox.
- Use a platform other than Dropbox.

**Comment by jeromelecoq** [comment]
Hi,

Can you try to download sub-folders? It seems to work on my end. This looks like a limitation of Dropbox given the size. 
Thanks!

**Comment by tmorshed** [comment]
Hi, yes, I actually ended up getting a free trial instead, and downloaded it that way. Just wanted to bring it to your attention.

Cheers,
Taha
